workflows:
  ios-workflow:
    name: iOS workflow
    instance_type: mac_pro
    environment:
      groups:
          - app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
      vars:      
        BUNDLE_ID: "io.myapp.ioniccordova" # <-- Put your Bundle Id here 
      xcode: latest
      node: v16.11.1
    working_directory: quasar-project
    scripts:
      - name: Build iOS
        script: |
            set -e
            yarn install
            yarn global add @quasar/cli
            ionic cordova platform remove ios 
            ionic cordova platform add ios --save
            npm i -g cordova-res
            ionic cordova resources ios --force
            quasar b -m ios

