workflows:
  ios-workflow:
    name: iOS workflow
    instance_type: mac_pro
    environment:
      groups:
          - app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
      vars:      
        BUNDLE_ID: "io.myapp.ioniccordova" # <-- Put your Bundle Id here 
      xcode: latest
      node: v16.11.1
    working_directory: quasar-project
    scripts:
      - name: Build iOS
        script: |
            set -e
            yarn install
            yarn global add @quasar/cli
            quasar build -m cordova -T ios -- --release --device --buildConfig='../build.json'
    artifacts:
      - /Users/builder/clone/src-cordova/platforms/ios/build/device/*.ipa
      - /Users/builder/clone/src-cordova/platforms/ios/build/device/*
      - /Users/builder/clone/platforms/ios/*
      - /Users/builder/clone/cordova/platforms/ios/build/device/*.ipa
      - /tmp/xcodebuild_logs/*.log
